name: Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - run: ./gradlew test
