name: UnitTest

on:
  push:
    branches: [ develop ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Unit Test
        run: ./gradlew test
